version: 2

updates:

  # # Npm
  - package-ecosystem: "npm"
    directory: "/cloudflare"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/hooks"
    schedule:
      interval: "daily"
